stages:
  - docs
  - deploy

# Common variables
variables:
  FEDORA_IMAGE: "registry.gitlab.gnome.org/gnome/gtk/fedora:v32"

reference:
  image: $FEDORA_IMAGE
  stage: docs
  needs: []
  script:
    - sh -x ./download-reference.sh
    - meson setup  _build
    - meson compile -C _build
    - mv _build/glib/glib/glib/ docs/glib/
    - mv _build/glib/gobject/gobject/ docs/gobject/
    - mv _build/glib/gio/gio/ docs/gio/
    - mv _build/gtk3/gdk/gdk3/ docs/gdk3/
    - mv _build/gtk3/gdk/gdk3-x11/ docs/gdk3-x11/
    - mv _build/gtk3/gtk/gtk3/ docs/gtk3/
    - mv _build/atk/atk/atk/ docs/atk/
    - mv _build/atk/atspi2/atspi2/ docs/atspi2/
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  needs: ['reference']
  script:
    - mkdir public
    - mv docs/* public/
    - cp static/* public/
  artifacts:
    paths:
      - public
